### ISSUE TITLE
Browser sync error

### ISSUE THREAD

**Issue by moeen-basra** [moeen-basra/laravel-react#6]
Some times on linux, when trying to run npm commands ```npm run watch-poll``` or ```npm run hot```
it throws following error.

```
events.js:136
      throw er; // Unhandled 'error' event
      ^

Error: watch app ENOSPC
    at _errnoException (util.js:1031:13)
    at FSWatcher.start (fs.js:1397:19)
    at Object.fs.watch (fs.js:1423:11)
    at createFsWatchInstance (/var/www/laravel-react/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/var/www/laravel-react/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/var/www/laravel-react/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/var/www/laravel-react/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/var/www/laravel-react/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/var/www/laravel-react/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:167:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! laravel-react@2.2.2 hot: `cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the laravel-react@2.2.2 hot script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by moeen-basra** [comment]
This happens when we cross the limit for the notifications watcher. following command fixes the issue.

```echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p```
